version: 1.0.{build}
branches:
  only:
    - master
    - devel

image: Visual Studio 2015
clone_folder: C:\projects\rtabmap
platform: x64
configuration: Release

init:
  - cmake --version
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

install:
  # Python for gdown
  - set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  - ps: py -m pip install gdown

  # Qt
  - set QTDIR=C:\Qt\5.10.1\msvc2015_64
  - set PATH=%QTDIR%\bin;%PATH%

  # PCL
  - ps: wget 'https://dl.dropboxusercontent.com/s/2iayr4lyqa50i9j/PCL_181_August2018_x64_vc14.exe?dl=0' -outfile pcl.exe
  - cmd: pcl.exe -o"C:\Program Files" -y
  - set PATH=%PATH%;C:\Program Files\PCL\bin

  # OpenCV
  - ps: wget 'https://dl.dropboxusercontent.com/s/o6ofn491bc0jso1/opencv450_vc14.exe?dl=0' -outfile opencv.exe
  - cmd: opencv.exe -o"C:\Program Files" -y
  - set PATH=%PATH%;C:\Program Files\opencv\x64\vc14\bin

  # FLANN
  - ps: wget 'https://dl.dropboxusercontent.com/s/7k58jbmqa51sxmh/FLANN-msvc140.exe?dl=0' -outfile flann.exe
  - cmd: flann.exe -o"C:\Program Files" -y

  # Eigen
  - ps: wget 'https://dl.dropboxusercontent.com/s/3v6i9i8dxj4o8ji/Eigen.exe?dl=0' -outfile eigen.exe
  - cmd: eigen.exe -o"C:\Program Files" -y

  # OpenNI2
  - ps: wget 'https://dl.dropboxusercontent.com/s/d98jv79l6oy9fxz/OpenNI2.exe?dl=0' -outfile openni2.exe
  - cmd: openni2.exe -o"C:\Program Files" -y
  - set PATH=%PATH%;C:\Program Files\OpenNI2\Redist

  # yaml-cpp
  - ps: wget 'https://dl.dropboxusercontent.com/s/22qfvftwj6zq8tj/yaml-cpp_x64_vc14.exe?dl=0' -outfile yaml.exe
  - cmd: yaml.exe -o"C:\Program Files" -y

  # libfreenect v1 (upload your ZIP somewhere public and replace link)
  - ps: wget 'https://www.dropbox.com/s/YOUR_LIBFREENECT_ZIP_HERE.zip?dl=1' -outfile freenect.zip
  - ps: Expand-Archive freenect.zip -DestinationPath "C:\Program Files\libfreenect"
  - set FREENECT_ROOT=C:\Program Files\libfreenect
  - set PATH=%PATH%;%FREENECT_ROOT%\bin

before_build:
  - cd C:\projects\rtabmap\build
  - set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;C:\Program Files\PCL\cmake
  - cmake -G "Visual Studio 14 2015 Win64" ^
      -DOpenCV_DIR="C:\Program Files\opencv\build" ^
      -DPCL_DIR="C:\Program Files\PCL\cmake" ^
      -DFREENECT_INCLUDE_DIR="%FREENECT_ROOT%\include\libfreenect" ^
      -DFREENECT_LIBRARY="%FREENECT_ROOT%\lib\freelibrary.lib" ^
      -DWITH_FREENECT=ON ^
      -DBUILD_AS_BUNDLE=ON ^
      -Dyaml-cpp_DIR="C:\Program Files\yaml-cpp\CMake" ^
      ..

build_script:
  - cmake --build . --config Release --target package

after_build:
  - ps: "ls build"
  - ps: "ls build\\bin"
  - ps: "ls build\\RTABMap-*-win64.exe"

artifacts:
  - path: build\RTABMap-*-win64.exe
    name: RTAB-Map-Installer

notifications:
  - provider: Email
    to:
      - matlabbe@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
