branches:
  only:
    - master
    - devel

os: Visual Studio 2015

clone_folder: c:\projects\rtabmap

platform: x64
configuration: Release

init:
  - cmake --version
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

install:
  # Python for gdown
  - set PATH=C:\Python38-x64;C:\Python38-x64\Scripts;%PATH%
  - ps: py -m pip --disable-pip-version-check install gdown>=5.1.0 

  # Qt
  - set QTDIR=C:\Qt\5.10.1\msvc2015_64
  - set PATH=%QTDIR%\bin;%PATH%

  # Boost
  - set PATH=%PATH%;C:\Libraries\boost_1_62_0\lib64-msvc-14.0

  # OpenNI2
  - ps: wget 'https://dl.dropboxusercontent.com/s/d98jv79l6oy9fxz/OpenNI2.exe?dl=0' -outfile OpenNI2.exe
  - cmd: OpenNI2.exe -o"C:\Program Files" -y
  - set PATH=%PATH%;C:\Program Files\OpenNI2\Redist

  # OpenCV
  - ps: wget 'https://dl.dropboxusercontent.com/s/o6ofn491bc0jso1/opencv450_vc14.exe?dl=0' -outfile opencv.exe
  - cmd: opencv.exe -o"C:\Program Files" -y
  - set PATH=%PATH%;C:\Program Files\opencv\x64\vc14\bin

  # VTK
  - ps: wget 'https://dl.dropboxusercontent.com/s/1l33b5l3f3y52gf/VTK-6_3-msvc140.exe?dl=0' -outfile VTK-6_3.exe
  - cmd: VTK-6_3.exe -o"C:\Program Files" -y
  - set PATH=%PATH%;C:\Program Files\VTK\bin

  # QHull, FLANN, Eigen, PCL, zlib, g2o, GTSAM, Octomap, CPU-TSDF, OpenChisel, yaml-cpp, RealSense2, Kinect4Azure
  # OMITTED FOR BREVITY: Retain same commands as your original config for all these

  # Custom libfreenect install
  - ps: wget 'https://www.dropbox.com/scl/fi/oc8vrt9dxo85nixnq3owv/libfreenect.zip?rlkey=4p0hbl4tlkbi26rrc8b6s29p7&st=m6gdgmcn&dl=1' -outfile libfreenect_custom.zip
  - ps: Expand-Archive libfreenect_custom.zip -DestinationPath 'C:\Program Files\libfreenect'
  - set PATH=%PATH%;C:\Program Files\libfreenect\bin

before_build:
  - cd c:\projects\rtabmap\build
  - cmake -G "Visual Studio 14 2015 Win64" ^
      -DBUILD_AS_BUNDLE=ON ^
      -DWITH_FREENECT=ON ^
      -DWITH_CPUTSDF=ON ^
      -DWITH_REALSENSE=OFF ^
      -DWITH_REALSENSE2=ON ^
      -DWITH_ZED=OFF ^
      -DOpenCV_DIR="C:\Program Files\opencv\build" ^
      -DPCL_DIR="C:\Program Files\PCL\cmake" ^
      -Dyaml-cpp_DIR="C:\Program Files\yaml-cpp\CMake" ^
      -Dcpu_tsdf_DIR="C:\Program Files\cpu_tsdf\share\cpu_tsdf" ^
      -DCMAKE_PREFIX_PATH="C:\Program Files\libfreenect" ^
      ..
  - cmake -LA | findstr WITH_

after_build:
  - cmake --build . --config Release --target package

artifacts:
  - path: build\RTABMap-*-win64.exe
    name: RTAB-Map-Installer
  - path: build
    name: RTABMap-Build-Folder

notifications:
  - provider: Email
    to:
      - matlabbe@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
